### ISSUE TITLE
Transform for CVUSA.

### ISSUE THREAD

**Issue by liguopeng0923** [xlwangDev/HC-Net#1]
Hi Xiaolong,

I have reproduced the Spherical Transform in VIGOR. However, it isn't easy to get a normal result in CVUSA. Whether there are additional operations in CVUSA？

Best,
Guopeng.

**Comment by guanfang12** [comment]
Because standard panoramic images should have a 2:1 aspect ratio, and the images in CVUSA are cropped with a non-standard aspect ratio, as mentioned in Section 4.4 of our paper:  

> Despite the panoramas in CVUSA being cropped and having a non-standard aspect ratio, our spherical transform method successfully projects them to a bird's-eye view by completing it to the correct proportion, as shown in Figure 5.

The code for this completion is as follows(we set dty = -20 for CVUSA):

```python
Hp, Wp = img.shape[0], img.shape[1] # pano shape

if dty != 0 or Wp != 2*Hp:

    ty = (Wp/2-Hp)/2 + dty                                                 # completing pano to the correct proportion

    matrix_K = np.array([[1,0,0],[0,1,ty],[0,0,1]])

    img = cv2.warpPerspective(img,matrix_K,(int(Wp),int(Hp+(Wp/2-Hp))))
```

Typically, cropping involves trimming the content of the vehicles within the field of view. You can also test the bird's-eye view projection of CVUSA panoramic images on our online test platform in Example 3 using the following [link](http://101.230.144.196:7860/).

**Comment by liguopeng0923** [comment]
Thanks very much. I have got successfully reasonable results according to your API. Great work!

**Comment by HaoDot** [comment]
Hi @liguopeng0923  and @guanfang12. I have set dty = -20 as your suggestion. But the transformation result is still strange like this. I also used cvusa dataset and the resolution of image is 224, 1232. Can you help me to fix it? Thanks for your time.
![image](https://github.com/user-attachments/assets/41df9881-fb04-451f-a226-abaaed8c550d)

**Comment by guanfang12** [comment]
> Hi @liguopeng0923 and @guanfang12. I have set dty = -20 as your suggestion. But the transformation result is still strange like this. I also used cvusa dataset and the resolution of image is 224, 1232. Can you help me to fix it? Thanks for your time. ![image](https://private-user-images.githubusercontent.com/75289266/378076484-41df9881-fb04-451f-a226-abaaed8c550d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0Mjg4ODMsIm5iZiI6MTcyOTQyODU4MywicGF0aCI6Ii83NTI4OTI2Ni8zNzgwNzY0ODQtNDFkZjk4ODEtZmIwNC00NTFmLWEyMjYtYWJhYWVkOGM1NTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDEyNDk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkMTRlMDZkMTc3MmNiODZjODE2ZjMyNTRmZmQ1NGRlZWRhNzMyZDdhNWExNjI0ZWQyNmRiMmJhM2M1MzFkZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eUxTa3q0Glw-qJ3BITmM1OWjTTLbH7t1_7Xe3J-Vt4g)

This is already the correct projection result. What you think is strange is because BEV projection assumes that all objects are on the ground, so objects higher than the ground will have unintuitive projection effects.
